from __future__ import annotations

CASES = [
    ("W2-T03-A", "W2", "native+hardware", "ReadyQueue empty + STOP"),
    ("W2-T03-B", "W2", "native", "WORK/STOP race immediately before wait"),
    ("W2-T03-C", "W2", "native+hardware", "dequeued READY + STOP => exact CANCEL"),
    ("W2-T03-D", "W2", "native+hardware", "PROCESSING current block + STOP"),
    ("W2-T05-A", "W2", "native+hardware", "Interference pending + STOP"),
    ("W2-T05-B", "W2", "native+hardware", "Interference running + STOP"),
    ("W2-ACK-A", "W2", "native", "duplicate/stale ACK cannot advance current STOP"),
    ("W2-ACK-B", "W2", "native", "last ACK wakes Communication; old tail cannot mutate"),
    ("W3-START-A", "W3", "native+hardware", "normal START publishes identity/gates before TIM2"),
    ("W3-START-B", "W3", "native", "invalid config causes no ownership/hardware mutation"),
    ("W3-T06-A", "W3", "native+hardware", "ADC/DBM arm failure rollback"),
    ("W3-T06-B", "W3", "native+hardware", "STOP before final START commit"),
    ("W3-START-C", "W3", "native+hardware", "final CommitStart failure leaves no RUNNING state"),
    ("W3-START-D", "W3", "native", "stale start ticket/generation rejected fail-closed"),
    ("W4-T04-A", "W4", "hardware", "half-filled DMA block + STOP"),
    ("W4-T04-B", "W4", "hardware", "pending TC at STOP edge"),
    ("W4-STOP-A", "W4", "native+hardware", "READY backlog cancellation"),
    ("W4-STOP-B", "W4", "native+hardware", "current PROCESSING completion"),
    ("W4-STOP-C", "W4", "hardware", "K1 DROP/recovery region + STOP"),
    ("W4-STOP-D", "W4", "native+hardware", "duplicate STOP during DMA quiesce"),
    ("W4-STOP-E", "W4", "hardware", "DMA/ADC error during quiesce => RESET_REQUIRED"),
    ("W5-T13-A", "W5", "native+hardware", "duplicate START same binding"),
    ("W5-T13-B", "W5", "native", "same request ID different binding => REQUEST_CONFLICT"),
    ("W5-T13-C", "W5", "native+hardware", "duplicate STOP"),
    ("W5-T13-D", "W5", "native+hardware", "old boot/session command rejected"),
    ("W5-T13-E", "W5", "native", "stale notification cannot mutate current generation"),
    ("W5-T13-F", "W5", "native", "stale worker ACK cannot complete current STOP"),
    ("W5-T13-G", "W5", "native+hardware", "last ACK immediate restart isolation"),
    ("W5-T20-A", "W5", "native+hardware", "result TX referenced => RESULT_BUSY"),
    ("W5-T20-B", "W5", "native+hardware", "released result allows next START"),
    ("W6-A", "W6", "hardware", "K8 NORMAL N256 repeated lifecycle"),
    ("W6-B", "W6", "hardware", "K1 DROP N256 repeated lifecycle"),
    ("W6-C", "W6", "hardware", "K4 NORMAL N512 lifecycle smoke"),
]
